name: Build
on:
  push:
    paths:
      - 'src/**'
      - '**.yml'
      - '**.xml'
      - '**.Dockerfile'
  pull_request:
    paths:
      - 'src/**'
      - '**.yml'
      - '**.xml'
      - '**.Dockerfile'
jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
        
      - name: Upload jacoco to Codecov
        uses: codecov/codecov-action@v3
        
      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.2
        with:
          paths: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Run PMD 
        run: mvn pmd:pmd
           
      - uses: pmd/pmd-github-action@v1
        with:
          rulesets: 'target/pmd/rulesets/maven-pmd-plugin-default.xml'
          analyzeModifiedFilesOnly: true
          
      - name: print pmd result
        uses: jwgmeligmeyling/pmd-github-action@master
        with:
          path: 'target/site/pmd/pmd.xml'
          
          
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: pmd-report.sarif


